#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const detectLang = require('language-detect');
const chalk = require('chalk').default;

// Get project name from directory
const projectName = path.basename(process.cwd());

// Function to detect languages from files in directory
function detectProjectLanguages() {
  try {
    const files = fs.readdirSync(process.cwd());
    const languages = new Set();
    
    files.forEach(file => {
      try {
        const filePath = path.join(process.cwd(), file);
        const stats = fs.statSync(filePath);
        
        if (stats.isFile()) {
          const detected = detectLang.sync(filePath);
          if (detected) languages.add(detected);
        }
      } catch (e) {
        // Skip files that can't be analyzed
      }
    });
    
    return Array.from(languages);
  } catch (e) {
    return [];
  }
}

// Detect languages from project files
const languages = detectProjectLanguages();
const languageBadges = languages.map(lang => {
  // Format language name for badge URL
  const formattedLang = encodeURIComponent(lang.toLowerCase());
  return `![${lang}](https://img.shields.io/badge/${formattedLang}-supported-green)`;
});

// Generate README content
const readmeContent = `# ${projectName}

${languageBadges.join(' ')}

## Description
Automatically generated by readme-generator. Edit this section to describe your project.

## Features
- Feature 1
- Feature 2

## Installation
\`\`\`bash
npm install
\`\`\`

## Usage
Explain how to use your project here
`;

// Write to file
fs.writeFileSync('README.md', readmeContent);
console.log(chalk.green('README.md successfully generated!'));